### ISSUE TITLE
Keyboard events don't fire on OS X unless in fullscreen

### ISSUE THREAD

**Issue by ConnerPetzold** [creationix/node-sdl#8]
It seems that the sdl window isn't being focused properly in os x.  All keyboard input is just sent to the terminal rather than to the apparently focused window.  It also doesn't seem to load as a full os x application as it doesn't show an icon in the dock and it doesn't modify the top os x toolbar.

I tried adding GrabInput (http://www.libsdl.org/docs/html/sdlwmgrabinput.html), but it doesn't seem to help: https://github.com/cpetzold/node-sdl/commit/b2e096d6e8f27fcca0b480b9c8add7e25cf97b4d#src/sdl.cc

**Comment by Freezerburn** [comment]
Keyboard events are being sent to the window just fine in a test application under the latest overhaul of the bindings. However, it still doesn't modify the top OS X toolbar or show a real icon in the dock. (though the dock icon probably has to do with needing to package the application a certain way) I'm not sure if you need to do something inside SDL to modify the toolbar, or if something else has to be done. I'll open a new issue about that.
